#!/usr/bin/env python3
"""Fallback commands used when no candidate is safely executable."""

import math
from typing import Optional, Sequence, Tuple

from .common import CandidateEvaluation, PerceptionData, PlannerCommand, PlannerConfig, PlannerState, Vec3


class FallbackManager:
    def __init__(self, config: Optional[PlannerConfig] = None):
        self.config = config or PlannerConfig()
        self._escape_side = 0.0
        self._escape_direction = Vec3()
        self._escape_forward = Vec3()

    def should_fallback(self, best: Optional[CandidateEvaluation], evaluations: Sequence[CandidateEvaluation], perception: PerceptionData) -> bool:
        if best is None:
            return True
        if not best.safety.feasible:
            return True
        return not any(item.safety.safe for item in evaluations)

    def command(self, state: PlannerState, perception: PerceptionData, evaluations: Sequence[CandidateEvaluation]) -> PlannerCommand:
        """Fallback used when the normal planner has no feasible command.

        Pure hover is safe, but it creates a deadlock in narrow passages.  Before
        using the generic body/world-frame lateral unstick, prefer explicit
        escape-like candidates generated by the frontend, because those preserve
        the local path/corridor intent better than a fresh nearest-obstacle
        lateral jump.
        """
        best = self._best_escape(evaluations)
        if perception.near_field_danger:
            self._escape_side = 0.0
            self._escape_direction = Vec3()
            self._escape_forward = Vec3()
            return PlannerCommand(Vec3(), "fallback_hover", "hover", "near_field_lidar_stop")

        explicit = self._best_explicit_escape(evaluations)
        if explicit is not None:
            speed = min(0.16, max(0.10, self.config.max_speed * 0.24))
            return PlannerCommand(
                explicit.trajectory.velocity.limit_norm(speed),
                "fallback_escape",
                explicit.trajectory.name,
                f"fallback_explicit_escape:{explicit.safety.reason}",
            )

        fallback = self._lateral_unstick_command(state, perception, best)
        if fallback is not None:
            reason = best.safety.reason if best is not None else "no_safe_candidate"
            return PlannerCommand(fallback, "fallback_escape", "fallback_lateral_unstick", f"fallback_unstick:{reason}")

        if best is not None:
            return PlannerCommand(Vec3(), "fallback_hover", "hover", f"fallback_stop:{best.safety.reason}")
        return PlannerCommand(Vec3(), "fallback_hover", "hover", "no_safe_candidate")

    def _lateral_unstick_command(
        self,
        state: PlannerState,
        perception: PerceptionData,
        best: Optional[CandidateEvaluation],
    ) -> Optional[Vec3]:
        if best is not None and best.safety.safe:
            self._escape_side = 0.0
            self._escape_direction = Vec3()
            self._escape_forward = Vec3()
            return None
        nearest = self._nearest_obstacle_body(state, perception)
        if nearest is None:
            return None
        obs_x, obs_y, clearance, away_x, away_y = nearest

        # Only unstick when the obstacle is in front and there is still enough
        # physical room.  If we are near contact, hover wins.
        if not (0.25 <= obs_x <= 4.5 and abs(obs_y) <= 1.8):
            if self._escape_direction.norm() > 1.0e-6 and clearance > 0.52 and best is not None and not best.safety.safe:
                lateral_speed = min(0.18, max(0.12, self.config.max_speed * 0.24))
                return self._escape_direction.limit_norm(1.0) * lateral_speed
            return None
        if clearance < 0.50:
            return None
        if self._escape_direction.norm() > 1.0e-6 and clearance > 0.52 and best is not None and not best.safety.safe:
            lateral_speed = min(0.18, max(0.12, self.config.max_speed * 0.24))
            return self._escape_direction.limit_norm(1.0) * lateral_speed
        if best is not None and best.safety.min_clearance < -0.05 and clearance < 0.52:
            return None

        if self._escape_forward.norm() <= 1.0e-6:
            ch = math.cos(state.heading)
            sh = math.sin(state.heading)
            self._escape_forward = Vec3(ch, sh, 0.0).normalized(Vec3(1.0, 0.0, 0.0))
        forward = self._escape_forward
        left = Vec3(-forward.y, forward.x, 0.0)

        # Keep a side latch, but choose the initial side from the world-frame
        # clearance gradient. Body-frame left/right can flip after an escape turn.
        if abs(self._escape_side) < 0.5:
            away = Vec3(away_x, away_y, 0.0)
            if away.norm() > 1.0e-6:
                self._escape_side = 1.0 if (left.x * away.x + left.y * away.y) >= 0.0 else -1.0
            elif abs(obs_y) < 0.10:
                self._escape_side = 1.0
            else:
                self._escape_side = -1.0 if obs_y > 0.0 else 1.0

        lateral = left * self._escape_side
        if self._escape_direction.norm() <= 1.0e-6:
            self._escape_direction = lateral.normalized(Vec3())

        # Distance-based unstick:
        # - far from the obstacle: pure lateral motion to change the viewpoint;
        # - medium distance: lateral plus a tiny backward component;
        # - close: no command, handled by the hover branch above.
        if clearance > 0.90:
            lateral_speed = min(0.20, max(0.14, self.config.max_speed * 0.28))
            back_speed = 0.0
        else:
            lateral_speed = min(0.18, max(0.12, self.config.max_speed * 0.24))
            back_speed = min(0.025, max(0.0, self.config.max_speed * 0.035))
        return lateral * lateral_speed - forward * back_speed

    def _nearest_obstacle_body(self, state: PlannerState, perception: PerceptionData) -> Optional[Tuple[float, float, float, float, float]]:
        nearest = None
        nearest_clearance = 999.0
        ch = math.cos(state.heading)
        sh = math.sin(state.heading)
        for obs in perception.obstacles:
            rel = obs.position_at(0.0) - state.position
            rel_xy = Vec3(rel.x, rel.y, 0.0)
            dist = rel_xy.norm()
            if dist <= 1.0e-6:
                continue
            clearance = dist - (self.config.drone_radius + float(obs.radius))
            if clearance >= nearest_clearance:
                continue
            nearest_clearance = clearance
            body_x = ch * rel.x + sh * rel.y
            body_y = -sh * rel.x + ch * rel.y
            nearest = (float(body_x), float(body_y), float(clearance), float(-rel.x), float(-rel.y))
        return nearest

    @staticmethod
    def _best_explicit_escape(evaluations: Sequence[CandidateEvaluation]) -> Optional[CandidateEvaluation]:
        allowed = []
        for item in evaluations:
            name = item.trajectory.name
            if not (
                name.startswith("local_escape:")
                or name.startswith("corridor_escape:")
                or name in {"side_left", "side_right", "back", "back_left", "back_right", "stop"}
            ):
                continue
            if item.safety.reason in {"hard_clearance_violation", "static_clearance_violation", "ttc_violation"}:
                continue
            if not item.safety.feasible and item.safety.min_clearance < -0.02:
                continue
            allowed.append(item)
        if not allowed:
            return None
        return min(
            allowed,
            key=lambda item: (
                0 if item.safety.feasible else 1,
                item.costs.get("reverse", 999.0),
                item.costs.get("progress", 999.0),
                item.costs.get("lateral", 999.0),
                -float(item.safety.min_static_clearance),
                -float(item.safety.min_clearance),
                item.score,
            ),
        )

    @staticmethod
    def _best_escape(evaluations: Sequence[CandidateEvaluation]) -> Optional[CandidateEvaluation]:
        if not evaluations:
            return None
        return max(
            evaluations,
            key=lambda item: (
                item.safety.safe,
                item.safety.feasible,
                item.safety.min_clearance,
                -item.score,
            ),
        )
